branches:
  only:
    - master
sudo: false
language: ruby
services:
  - mysql
  - postgresql
env:
  global:
    - APP_SECRET_TOKEN=b2724973fd81c2f4ac0f92ac48eb3f0152c4a11824c122bcf783419a4c51d8b9bba81c8ba6a66c7de599677c7f486242cf819775c433908e77c739c5c8ae118d
  matrix:
    - DATABASE_ADAPTER=mysql2
    - DATABASE_ADAPTER=postgresql DATABASE_USERNAME=postgres
rvm:
  - 2.4.9
  - 2.5.7
  - 2.6.5
jobs:
  include:
    - rvm: 2.6.5
      script: bundle exec rubocop
cache: bundler
script: bundle exec rake
notifications:
  email: false
  webhooks:
    urls:
      - "https://devbot.gottsnack.net/services/hooks/dHJhdmlzY2k"
    on_success: change # always|never|change
    on_failure: always
    on_start: never
